apiVersion: v1
kind: Pod
metadata:
  name: skala-webserver
  namespace: class-0
  labels:
    app: skala-webserver
spec:
  containers:
  - name: webserver
    image: skala-registry.skala-ai.com/skala25a/skala-webserver:1.0 
    imagePullPolicy: Always
    env:
    - name: USER_NAME
      value: skala
