apiVersion: apps/v1
kind: Deployment
metadata:
  name: skala-deploy-test
  namespace: class-0
  labels:
    app: skala-deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skala-deploy-test
  template:
    metadata:
      annotations:
        update: 1639bd93
      labels:
        app: skala-deploy-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          env:
            - name: USER_NAME
              value: skala

