apiVersion: v1
kind: Pod
metadata:
  generateName: skala-pod-test-
  namespace: class-0
  labels:
    app: skala-pod-test
spec:
  serviceAccountName: default
  containers:
  - name: nginx
    image:  nginx:latest
    imagePullPolicy: Always
    env:
    - name: USER_NAME
      value: skala
