apiVersion: apps/v1
kind: Deployment
metadata:
  name: skala-linux-kubectl
  namespace: class-0
  labels:
    app: skala-linux-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skala-linux-kubectl
  template:
    metadata:
      labels:
        app: skala-linux-kubectl
    spec:
      containers:
        - name: linux
          image: skala-registry.skala-us.com/skala-linux-kubectl:1.0
          imagePullPolicy: Always
          env:
            - name: KUBECONFIG
              value: /root/.kube/config
          volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: kubeconfig
          configMap:
            name: skala-linux-kubeconfig
            defaultMode: 0600
