apiVersion: v1
kind: Pod
metadata:
  name: skala-pvc-handler-pod
  namespace: class-0
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/bash","-lc","apt-get update && apt-get install -y vim sudo && tail -f /dev/null"]
    volumeMounts:
    - name: efs-config
      mountPath: /config
  volumes:
  - name: efs-config
    persistentVolumeClaim:
      claimName: skala-efs-sc-myfirst-api-server-pvc
