apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skala-efs-sc-myfirst-api-server-pvc
  namespace: class-0
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: efs-sc-shared
