apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk0199-myfirst-api-server
  namespace: class-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk0199-myfirst-api-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 36718fc8
      labels:
        app: sk0199-myfirst-api-server
    spec:
      serviceAccountName: default
      containers:
      - name: myfirst-api-server
        image: skala-registry.skala-ai.com/class-0/sk0199-myfirst-api-server:1.0.0
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: sk0199
        - name: NAMESPACE
          value: class-0
        - name: SPRING_PROFILES_ACTIVE  
          value: "prod"  

        #PVC를 /app/config로 마운트
        volumeMounts:
        - name: efs-config
          mountPath: /app/config
          readOnly: true

      volumes:
      - name: efs-config
        persistentVolumeClaim:
          claimName: sk0199-efs-sc-myfirst-api-server-pvc
