apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk0199-deploy-test
  namespace: class-0
  labels:
    app: sk0199-deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk0199-deploy-test
  template:
    metadata:
      annotations:
        update: 36718fc8
      labels:
        app: sk0199-deploy-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          env:
            - name: USER_NAME
              value: sk0199

