apiVersion: apps/v1
kind: Deployment
metadata:
  name: skala-myfirst-api-server
  namespace: class-0
  labels:
    app: skala-myfirst-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skala-myfirst-api-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/actuator/prometheus'
        update: e5644ccb
      labels:
        app: skala-myfirst-api-server
    spec:
      containers:
      - name: webserver
        image: skala-registry.skala-us.com/class-0/skala-webserver:1.0
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: skala
        - name: NAMESPACE
          value: class-0
        - name: SPRING_PROFILES_ACTIVE  
          value: "local"  
